# Generated by Django 3.1.7 on 2021-02-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Game name')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('game', models.ForeignKey(default='default_game', on_delete=django.db.models.deletion.CASCADE, related_name='session_game', to='game_bot.games')),
            ],
        ),
        migrations.CreateModel(
            name='GameScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(default='default_game', on_delete=django.db.models.deletion.CASCADE, related_name='scores_game', to='game_bot.games', to_field='name')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='game_bot.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
