# Generated by Django 3.1.7 on 2021-02-25 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_bot', '0002_auto_20210225_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='game',
            field=models.ForeignKey(default='default_game', on_delete=django.db.models.deletion.CASCADE, related_name='scores_game', to='game_bot.games', to_field='name'),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
